---
title: "Analysis on Models with Contact Network Features"
author: "Coco Yu"
date: "`r lubridate::today()`"
format:
  html:
    toc: true 
    toc_depth: 4
    embed-resources: true
editor_options: 
  chunk_output_type: console
---

### Setup

Chunk Defaults
```{r}
knitr::opts_chunk$set(attr.output='style="max-height: 500px;"')

suppressPackageStartupMessages(library(tidyposterior))
library(tidyverse)
library(tidymodels)
options(conflicts.policy = "depends.ok")
source("https://github.com/jjcurtin/lab_support/blob/main/fun_ml.R?raw=true")

library(kableExtra, exclude = "group_rows")
library(lubridate)
library(janitor, include.only = c("tabyl", "clean_names"))
library(Matrix, exclude = c("expand", "pack", "unpack"))
library(poissonreg)
library(DALEX, exclude= "explain")
library(DALEXtra)

theme_set(theme_classic()) 
```

Absolute Paths 
```{r}
source("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")
source("https://github.com/jjcurtin/lab_support/blob/main/fun_eda.R?raw=true")
source("https://github.com/jjcurtin/lab_support/blob/main/fun_plots.R?raw=true")
source("_lib/ana_models.R")

path_network <- format_path(str_c("risk/data_processed/network"))
path_models <- format_path(str_c("risk/models/network"))
```

### Read in Data

```{r}
fits_glmnet <- read_rds(here::here(path_models, "fits_lst_glmnet_v1.rds"))
err_tbl_glmnet <- read_csv("_results/err_tbl_glmnet_v1.csv")
best_glmnet <- read_rds(here::here(path_models, "best_models_glmnet_v1.rds"))
fits_xgboost <- read_rds(here::here(path_models, "fits_lst_xgboost_v1.rds"))
err_tbl_xgboost <- read_csv("_results/err_tbl_xgboost_v1.csv")
best_xgboost <- read_rds(here::here(path_models, "best_models_xgboost_v1.rds"))
fits_rf <- read_rds(here::here(path_models, "fits_lst_rf_v1.rds"))
err_tbl_rf <- read_csv("_results/err_tbl_rf_v1.csv")
best_rf <- read_rds(here::here(path_models, "best_models_rf_v1.rds"))

labels <- read_csv(here::here(path_network, "labels.csv"))
features_baseline <- read_csv(here::here(path_network, "features_baseline.csv"))
```

**Combine and clean up results**

```{r}
err_tbl <- err_tbl_glmnet |> 
  bind_rows(err_tbl_xgboost) |> 
  bind_rows(err_tbl_rf) |> 
  mutate(id = row_number())

fits <- c(fits_glmnet, fits_xgboost, fits_rf)
best_models <- c(best_glmnet, best_xgboost, best_rf)
```

### Bayesian Comparison

#### Continuous Outcomes

```{r}
id_continuous_baseline <- err_tbl |> 
  filter(outcome == "continuous" & str_detect(feature_version, "baseline")) |> 
	arrange(desc(rsq_median)) |> 
	slice_head(n = 1) |> 
	pull(id) |> 
	as.numeric()

id_continuous_full <- err_tbl |> 
	filter(outcome == "continuous" & str_detect(feature_version, "full")) |> 
	arrange(desc(rsq_median)) |> 
	slice_head(n = 1) |> 
	pull(id) |> 
	as.numeric()

baseline_continuous <- best_config_metrics(
	fits[[id_continuous_baseline]], metric = "rsq")
full_continuous <- best_config_metrics(
	fits[[id_continuous_full]], metric = "rsq")
```

```{r}
pp_continuous <- get_posterior(baseline_continuous, full_continuous)
```

```{r}
sum_perf(pp_continuous)
plot_contrast(pp_continuous)
contrast_perf(pp_continuous)
```

#### Binary

```{r}
id_binary_baseline <- err_tbl |> 
  filter(str_detect(outcome, "binary") & 
           str_detect(feature_version, "baseline")) |> 
	arrange(desc(roc_auc_median)) |> 
	slice_head(n = 1) |> 
	pull(id) |> 
	as.numeric()

id_binary_full <- err_tbl |> 
	filter(str_detect(outcome, "binary") & 
	         str_detect(feature_version, "full")) |> 
	arrange(desc(roc_auc_median)) |> 
	slice_head(n = 1) |> 
	pull(id) |> 
	as.numeric()

baseline_binary <- best_config_metrics(
	fits[[id_binary_baseline]], metric = "roc_auc")
full_binary <- best_config_metrics(
	fits[[id_binary_full]], metric = "roc_auc")
```

```{r}
pp_binary <- get_posterior(baseline_binary, full_binary)
```

```{r}
sum_perf(pp_binary)
plot_contrast(pp_binary)
contrast_perf(pp_binary)
```

### Interpretation

### Continuous

```{r}
err_tbl |> slice(id_continuous_full) |> print_kbl()
data_continuous <- read_csv(here::here(path_network, 
                                       "features_network_v4.csv")) |> 
  left_join(labels, by = "subid") |>
            mutate(lapse = as.integer(n_lapse / day_on_study * 91)) |> 
            left_join(features_baseline |> select(subid, starts_with("demo")), 
                      by = "subid") |>
            select(-n_lapse, -day_on_study, -subid) |> 
  glimpse()

rec <- recipe(lapse ~ ., data = data_continuous) |> 
      step_select(-starts_with("n_")) |> 
      step_impute_median(all_numeric_predictors()) |> 
      step_impute_mode(all_nominal_predictors()) |>
      step_dummy(all_nominal_predictors()) |> 
      step_zv(all_predictors()) |> 
      step_nzv(all_predictors()) |>
      step_normalize(all_numeric_predictors())

feat <- rec |> prep(data_continuous) |> bake(new_data = NULL)

best_model_continuous <- best_models[[id_continuous_full]]
best_model_continuous |> 
  tidy() |> 
  arrange(desc(abs(estimate))) |>
  print_kbl()
```

```{r}
predict_wrapper <- function(model, newdata) {
  predict(model, newdata) |> 
    pull(.pred)
}

get_shaps <- function(df1){
  predict_parts(explain_full, 
                new_observation = df1,
                type = "shap",
                B = 25) |> 
    filter(B == 0) |> 
    select(variable_name, variable_value, contribution) |> 
    as_tibble()
}

explain_full <- explain_tidymodels(best_model_continuous,  
                                   data = feat, 
                                   y = data_continuous$lapse, 
                                   predict_function = predict_wrapper)

local_shap_continuous <- feat |>
  select(-lapse) |> 
  slice_sample(prop = 1/5) |>
  mutate(id = row_number()) |>
  nest(.by = id, .key = "dfs") |> 
  mutate(shaps = map(dfs, \(df1) get_shaps(df1))) |> 
  select(-dfs) |>
  unnest(shaps)

local_shap_continuous |>
  mutate(contribution = abs(contribution)) |>
  group_by(variable_name) |>
  summarize(mean_shap = mean(contribution)) |>
  arrange(desc(mean_shap)) |>
  mutate(variable_name = factor(variable_name),
         variable_name = fct_reorder(variable_name, mean_shap)) |>
  ggplot(aes(x = variable_name, y = mean_shap)) +
  geom_point() +
  coord_flip()

```

### Binary

```{r}
err_tbl |> slice(id_binary_full) |> print_kbl()
data_binary <- read_csv(here::here(path_network, 
                                       "features_network_v3.csv")) |>
  left_join(labels, by = "subid") |> 
            mutate(lapse = if_else(n_lapse/day_on_study < .15, "no", "yes")) |> 
            left_join(features_baseline |> select(subid, starts_with("demo")), 
                      by = "subid") |>
            select(-n_lapse, -day_on_study, -subid)

rec <- recipe(lapse ~ ., data = data_binary) |> 
      step_select(-starts_with("n_")) |> 
      step_impute_median(all_numeric_predictors()) |> 
      step_impute_mode(all_nominal_predictors()) |> 
      step_dummy(all_nominal_predictors()) |> 
      themis::step_upsample(lapse, over_ratio = 1) |> 
      step_zv(all_predictors()) |> 
      step_nzv(all_predictors()) |>
      step_normalize(all_numeric_predictors())

feat <- rec |> prep(data_binary) |> bake(new_data = NULL)

best_model_binary <- best_models[[id_binary_full]]
best_model_binary |> 
  tidy() |> 
  arrange(desc(abs(estimate))) |>
  print_kbl()
```

```{r}
predict_wrapper <- function(model, newdata) {
  predict(model, newdata, type = "prob") |> 
    pull(.pred_yes)
}
explain_full <- explain_tidymodels(best_model_binary,  
                                   data = feat, 
                                   y = data_binary$lapse, 
                                   predict_function = predict_wrapper)

local_shap_binary <- feat |>
  select(-lapse) |>
  slice_sample(prop = 1/5) |>
  mutate(id = row_number()) |>
  nest(.by = id, .key = "dfs") |> 
  mutate(shaps = map(dfs, \(df1) get_shaps(df1))) |> 
  select(-dfs) |>
  unnest(shaps)

local_shap_binary |>
  mutate(contribution = abs(contribution)) |>
  group_by(variable_name) |>
  summarize(mean_shap = mean(contribution)) |>
  arrange(desc(mean_shap)) |>
  mutate(variable_name = factor(variable_name),
         variable_name = fct_reorder(variable_name, mean_shap)) |>
  ggplot(aes(x = variable_name, y = mean_shap)) +
  geom_point() +
  coord_flip()
```

```{r}

```

