---
title: "GLMNET Models"
author: "Coco Yu"
date: "`r lubridate::today()`"
format:
  html:
    toc: true 
    toc_depth: 4
    embed-resources: true
editor_options: 
  chunk_output_type: console
---

### Setup

Chunk Defaults
```{r}
knitr::opts_chunk$set(attr.output='style="max-height: 500px;"')

library(tidyverse)
library(tidymodels)
options(conflicts.policy = "depends.ok")
source("https://github.com/jjcurtin/lab_support/blob/main/fun_ml.R?raw=true")

library(kableExtra, exclude = "group_rows")
library(lubridate)
library(janitor, include.only = c("tabyl", "clean_names"))
library(Matrix, exclude = c("expand", "pack", "unpack"))
library(poissonreg)

theme_set(theme_classic()) 
```

Absolute Paths 
```{r}
source("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")
source("https://github.com/jjcurtin/lab_support/blob/main/fun_eda.R?raw=true")
source("https://github.com/jjcurtin/lab_support/blob/main/fun_plots.R?raw=true")
source("_lib/run_models.R")
source("_lib/update_results.R")
source("_lib/ana_models.R")

# path_shared <- format_path(str_c("risk/data_processed/shared"))
path_network <- format_path(str_c("risk/data_processed/network"))
path_models <- format_path(str_c("risk/models/network"))
```

### Read in Data

```{r}
features_v1 <- read_csv(here::here(path_network, "features_network_v1.csv"))
features_v2 <- read_csv(here::here(path_network, "features_network_v2.csv"))
features_v3 <- read_csv(here::here(path_network, "features_network_v3.csv"))
features_v4 <- read_csv(here::here(path_network, "features_network_v4.csv"))
labels <- read_csv(here::here(path_network, "labels.csv"))
baseline <- read_csv(here::here(path_network, "features_baseline.csv"))
```

```{r}
features <- list(features_v1, features_v2, features_v3, features_v4)
feature_versions <- c(
                   "features_contact_v1", "features_contact_v2", 
                   "features_contact_v3", "features_contact_v4",
                   "features_full_v1", "features_full_v2", 
                   "features_full_v3", "features_full_v4")

configs <- tibble()
```

**Baseline**

```{r}
configs <- configs |> bind_rows(expand.grid(
  data_lst = list(baseline |> 
    select(subid, starts_with("demo")) |> 
    left_join(labels, by = "subid") |>
    mutate(lapse = as.integer(n_lapse / day_on_study * 91)) |> 
    select(-n_lapse, -day_on_study, -subid) |>
    glimpse()),
  feature_versions = "features_baseline",
  outcome_lst = "continuous",
  model_lst = c("poisson", "normal"),
  feature_lst = "baseline"
))

configs <- configs |> bind_rows(expand.grid(
  data_lst = list(baseline |> 
    select(subid, starts_with("demo")) |> 
    left_join(labels, by = "subid") |>
    mutate(lapse = if_else(n_lapse/day_on_study < .15, "no", "yes")) |> 
    select(-n_lapse, -day_on_study, -subid) |>
    glimpse()),
  feature_versions = "features_baseline",
  outcome_lst = "binary",
  model_lst = "logistic",
  feature_lst = "baseline"
))
```

**Contact Features**
```{r}
configs <- configs |> bind_rows(
  tibble(
    data_lst = features |> 
      map(\(feature)
          feature |> 
            left_join(labels, by = "subid") |>
            mutate(lapse = as.integer(n_lapse / day_on_study * 91)) |>
            select(-n_lapse, -day_on_study, -subid)),
    feature_versions = feature_versions[1:4],
    outcome_lst = "continuous"
  ) |> expand_grid(
    model_lst = c("poisson", "normal"),
    feature_lst = c("raw", "prop", "all")
  )
) |> bind_rows(
  tibble(
    data_lst = features |> 
      map(\(feature)
          feature |> 
            left_join(labels, by = "subid") |>
            mutate(lapse = if_else(n_lapse/day_on_study < .15, "no", "yes")) |>
            select(-n_lapse, -day_on_study, -subid)),
    feature_versions = feature_versions[1:4],
    outcome_lst = "binary"
  ) |> expand_grid(
    model_lst = "logistic",
    feature_lst = c("raw", "prop", "all")
  )
)
```

**Full Features**

```{r}
configs <- configs |> bind_rows(
  tibble(
    data_lst = features |> 
      map(\(feature)
          feature |> 
            left_join(labels, by = "subid") |>
            mutate(lapse = as.integer(n_lapse / day_on_study * 91)) |> 
            left_join(baseline |> select(subid, starts_with("demo")), 
                      by = "subid") |>
            select(-n_lapse, -day_on_study, -subid)),
    feature_versions = feature_versions[5:8],
    outcome_lst = "continuous"
  ) |> expand_grid(
    model_lst = c("poisson", "normal"),
    feature_lst = c("raw", "prop", "all")
  )
) |> bind_rows(
  tibble(
    data_lst = features |> 
      map(\(feature)
          feature |> 
            left_join(labels, by = "subid") |> 
            mutate(lapse = if_else(n_lapse/day_on_study < .15, "no", "yes")) |> 
            left_join(baseline |> select(subid, starts_with("demo")), 
                      by = "subid") |>
            select(-n_lapse, -day_on_study, -subid)),
    feature_versions = feature_versions[5:8],
    outcome_lst = "binary"
  ) |> expand_grid(
    model_lst = "logistic",
    feature_lst = c("raw", "prop", "all")
  )
)
```

### Modeling 

```{r}
err_tbl <- tibble()
best_models <- list()
fits_lst <- list()
```

```{r}
map(
  1:nrow(configs),
  \(i)
  update_results(
    run_glmnet(
      data = configs$data_lst[[i]],
      outcome = configs$outcome_lst[[i]],
      model = configs$model_lst[[i]],
      feature_set = configs$feature_lst[[i]]
    ),
    feature_version = configs$feature_versions[[i]]
  )
)

```

```{r}
err_tbl |>
  write_csv("_results/err_tbl_glmnet_v1.csv")

fits_lst |>
  write_rds(here::here(path_models, "fits_lst_glmnet_v1.rds"))

best_models |> 
  write_rds(here::here(path_models, "best_models_glmnet_v1.rds"))
```


